"""create all tables from sqlalchemy models

Revision ID: 0b916e429093
Revises: 
Create Date: 2026-06-28 15:12:29.618871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b916e429093'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('packets',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('protocol', sa.String(length=10), nullable=False),
    sa.Column('source_ip', sa.String(length=50), nullable=False),
    sa.Column('source_port', sa.Integer(), nullable=True),
    sa.Column('dest_ip', sa.String(length=50), nullable=False),
    sa.Column('dest_port', sa.Integer(), nullable=True),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('payload_size', sa.Integer(), nullable=False),
    sa.Column('flags', sa.String(length=20), nullable=True),
    sa.Column('icmp_type', sa.Integer(), nullable=True),
    sa.Column('icmp_code', sa.Integer(), nullable=True),
    sa.Column('matched', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_packets_dest_ip'), 'packets', ['dest_ip'], unique=False)
    op.create_index(op.f('ix_packets_id'), 'packets', ['id'], unique=False)
    op.create_index(op.f('ix_packets_matched'), 'packets', ['matched'], unique=False)
    op.create_index(op.f('ix_packets_protocol'), 'packets', ['protocol'], unique=False)
    op.create_index(op.f('ix_packets_source_ip'), 'packets', ['source_ip'], unique=False)
    op.create_index(op.f('ix_packets_timestamp'), 'packets', ['timestamp'], unique=False)
    op.create_table('signatures',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('protocol', sa.Enum('TCP', 'UDP', 'ICMP', 'ANY', name='protocoltype'), nullable=False),
    sa.Column('source_ip', sa.String(length=50), nullable=True),
    sa.Column('source_port', sa.String(length=50), nullable=True),
    sa.Column('dest_ip', sa.String(length=50), nullable=True),
    sa.Column('dest_port', sa.String(length=50), nullable=True),
    sa.Column('pattern', sa.Text(), nullable=True),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severitylevel'), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('reference', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signatures_category'), 'signatures', ['category'], unique=False)
    op.create_index(op.f('ix_signatures_enabled'), 'signatures', ['enabled'], unique=False)
    op.create_index(op.f('ix_signatures_id'), 'signatures', ['id'], unique=False)
    op.create_index(op.f('ix_signatures_name'), 'signatures', ['name'], unique=True)
    op.create_index(op.f('ix_signatures_severity'), 'signatures', ['severity'], unique=False)
    op.create_table('users',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('alerts',
    sa.Column('signature_id', sa.Integer(), nullable=False),
    sa.Column('source_ip', sa.String(length=50), nullable=False),
    sa.Column('source_port', sa.Integer(), nullable=True),
    sa.Column('dest_ip', sa.String(length=50), nullable=False),
    sa.Column('dest_port', sa.Integer(), nullable=True),
    sa.Column('protocol', sa.String(length=10), nullable=False),
    sa.Column('payload_snippet', sa.Text(), nullable=True),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severitylevel'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('packet_count', sa.Integer(), nullable=False),
    sa.Column('raw_packet', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['signature_id'], ['signatures.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_dest_ip'), 'alerts', ['dest_ip'], unique=False)
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_alerts_signature_id'), 'alerts', ['signature_id'], unique=False)
    op.create_index(op.f('ix_alerts_source_ip'), 'alerts', ['source_ip'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_index(op.f('ix_alerts_timestamp'), 'alerts', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alerts_timestamp'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_source_ip'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_signature_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_dest_ip'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_signatures_severity'), table_name='signatures')
    op.drop_index(op.f('ix_signatures_name'), table_name='signatures')
    op.drop_index(op.f('ix_signatures_id'), table_name='signatures')
    op.drop_index(op.f('ix_signatures_enabled'), table_name='signatures')
    op.drop_index(op.f('ix_signatures_category'), table_name='signatures')
    op.drop_table('signatures')
    op.drop_index(op.f('ix_packets_timestamp'), table_name='packets')
    op.drop_index(op.f('ix_packets_source_ip'), table_name='packets')
    op.drop_index(op.f('ix_packets_protocol'), table_name='packets')
    op.drop_index(op.f('ix_packets_matched'), table_name='packets')
    op.drop_index(op.f('ix_packets_id'), table_name='packets')
    op.drop_index(op.f('ix_packets_dest_ip'), table_name='packets')
    op.drop_table('packets')
    # ### end Alembic commands ###
